#!/usr/bin/env bash
# Configures nginx to add a custom X-Served-By header set to the server's hostname
export DEBIAN_FRONTEND=noninteractive

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sed -i '/listen 80 default_server;/a\        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

service nginx restart
